Add new sites in configuration #16
hunkimForks/chatgpt-arxiv-extension pull request #24
Opened 2023-02-21 14:42 UTC by yeeeqichen

Issue #16 

I add site configurations in the option page, enabling users to customize the arxivGPT for their own. Here is the preview:

![image](https://user-images.githubusercontent.com/50070891/220374585-a5aced2e-9c0b-435b-905b-2aac556847a9.png)

![image](https://user-images.githubusercontent.com/50070891/220374652-a0b3104b-5306-40ff-a5ee-ddf451f193b9.png)

However, there are a few more things that still need to be done:
- re-arrange the layout in the option page to make it prettier
- Pre-modify the manifest.json to support several possible sites that users could configure in the option page

Looking forward to your suggestions!

2023-02-21 23:24 UTC, hunkim commented
Wow~ This is really good! @joonhok-fittube @yanggak12 code review?

2023-02-22 03:52 UTC, joonhok-fittube commented
Sure, @yanggak12. I will take a look today!

On Wed, Feb 22, 2023, 06:25 Sung Kim ***@***.***> wrote:

> Wow~ This is really good! @joonhok-fittube
> <https://github.com/joonhok-fittube> @yanggak12
> <https://github.com/yanggak12> code review?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hunkimForks/chatgpt-arxiv-extension/pull/24#issuecomment-1439222397>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUMR2FYRQD4FHVDI47BNLILWYVFFNANCNFSM6AAAAAAVDEJ4UE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-22 08:06 UTC, joonhok-fittube requested changes
@yanggak12 I finished my review. Please have a look.

2023-02-22 08:06 UTC, joonhok-fittube commented on src/options/App.tsx
> +            supportedURLs[supportedURLs.length] = update.site
It's always better to keep objects immutable. Please create a new object from old one and use it instead.

2023-02-22 08:06 UTC, joonhok-fittube commented on src/options/App.tsx
> +                    supportedURLs[index] = URL
Please create a new object instead of updating old one.

2023-02-22 08:06 UTC, joonhok-fittube commented on src/options/App.tsx
> +                    supportedURLs.splice(index, 1)
Please keep objects immutable and create a new object instead of updating old one.

2023-02-22 08:06 UTC, joonhok-fittube commented on src/options/SiteCard.tsx
> +      setURLValue(URL)
Those values are already there. You don't have to set them here again.

2023-02-22 08:06 UTC, joonhok-fittube commented on src/options/SiteCard.tsx
> +          onClick={() => onClickSave(URLValue, promptValue, bodyTagValue, displayTagValue)}
You don't have to pass `URLValue`, `promptValue`, and so on.

2023-02-22 08:28 UTC, yeeeqichen commented
> @yeeeqichen I finished my review. Please have a look.

Thanks! I'll consider these suggestions and fix them.

2023-02-22 08:33 UTC, joonhok-fittube commented
@yeeeqichen Regarding updating the `package.json` file, you can actually inject

2023-02-22 08:36 UTC, joonhok-fittube commented
I am sorry I closed this PR by mistake. Reopening it.

2023-02-22 11:01 UTC, yeeeqichen commented
> @yeeeqichen Regarding updating the `package.json` file, you can actually configure it at run time. Check below page for more details.
> 
> https://developer.chrome.com/docs/extensions/mv3/content_scripts/#functionality

Got it!

2023-02-23 02:35 UTC, joonhok-fittube commented
@yeeeqichen Please ping me again when you finish your work and it's ready
to review.

> Message ID: <hunkimForks/chatgpt-arxiv-extension/pull/24/c1440082928@
> github.com>
>

2023-02-23 07:56 UTC, yeeeqichen commented
> 

Okay!

2023-02-23 13:04 UTC, yeeeqichen commented
@joonhok-fittube . Now I finish the changes, please have a look~ 

BTW, I'm quite busy these days and I'm not vey familiar with the the chrome plug-in. So I need more time to study the way how to enable updating `manifest.json` during run-time according to 'https://developer.chrome.com/docs/extensions/mv3/content_scripts/#functionality'

2023-02-24 04:22 UTC, joonhok-fittube commented
@yeeeqichen 

I am afraid that this change might confuse users without the corresponding `manifest.json` related change. Because the script will not run on sites user added in their configuration, hence makes no changes on those sites.

I suggest we wait for you or new contributors to take this PR and finish the change before proceeding. @hunkim  What do you think?

2023-02-25 05:24 UTC, hunkim commented
@joonhok-fittube I think we need to add https://*/* or something.

2023-02-27 15:03 UTC, yanggak12 reviewed
Hi there. 
I apologize for the late response.  
You've added a very interesting feature! 

I haven't finished reading the entire code of the arxiv extension yet, so rather than review the logic, I've left a comment recommending what I think is a better way to use Typescript.

2023-02-28 09:20 UTC, yeeeqichen commented on src/config.ts
> +export const defaultSiteConfigs: object = {
That really helps! To be honest, I just start to learn Typescript and am still not very familiar with these new features compared to conventional javascript.

2023-03-12 22:35 UTC, itsbrex commented
> @joonhok-fittube I think we need to add https://_/_ or something.

Have a look at https://github.com/fregante/webext-dynamic-content-scripts

2024-06-30 05:00 UTC, closed without merging